from marshmallow import fields
from app import ma
<<<<<<< HEAD


=======
>>>>>>> b88c7a79fcad71aab134413d103c3957ae0d80c5


class CustomerSchema(ma.Schema):
    id = fields.Integer(required=False) #Primary Key is Autogenerated and doesn't need to be apart of the payload
    first_name = fields.String(required=True)
    last_name = fields.String(required=True)
    username = fields.String(required=True)
    email = fields.Email(required=True)
    phone = fields.Integer(required=True)
    city = fields.String(required=True)
    state = fields.String(required=True)
    zip_code = fields.Integer(required=True)
    profile_pic = fields.String()


    class Meta: 
        fields = ("id", "first_name", "last_name","username", "email", "phone", "city", "state", "zip_code", "profile_pic")


customer_schema = CustomerSchema()
customers_schema = CustomerSchema(many=True)
